skip_commits:
  files:
    - README.md

image: Visual Studio 2017

services:
  - iis
  - mssql2014rs

environment:
  NugetApiKey:
    secure: DIE2y66RzXWvp2Q0wIOLlBTjxILBGeHyyg3pjwWjdVrggzuj9BuMWCdfHFmt9nt2
  PowershellGalleryApiKey:
    secure: IpwbqCY/2gU1iKYzF6bPJtILUY789f9fpgt+zP0LRrOK5Y3JXajA5yk/XaRkVjuy
  GithubAuthToken:
    secure: PkFAZB6f1lwOR9i3Mn9mR+kQBszikFVxmrhtOGK7p/xKlVF8o/htJc9LSQDSi3bN
  PSCIWinRmUser: PSCIUser
  PSCIWinRmPassword: PSCI$Password0X!
  APPVEYOR_RDP_PASSWORD: RDCPsci$Password0X!
    
init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name"
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
        $env:packageVersion = "$env:APPVEYOR_REPO_TAG_NAME" 
      }
  - git config --global core.autocrlf true
  
install:
  - ps: net user $env:PSCIWinRmUser $env:PSCIWinRmPassword /add /y 
  - ps: net localgroup administrators $env:PSCIWinRmUser /add
  - ps: . ./PSCI/bat/PSRemoting/Enable-Remoting.ps1; Set-ExecutionPolicy RemoteSigned -Force; Enable-Remoting
# this is to reinstall webdeploy with Remote Agent Service enabled  
  - choco install webdeploy -y   
  - choco uninstall webdeploy
  - choco install webdeploy -y 

build_script:
  - ps: ./build/build.ps1

test: off
  
artifacts:
  - path: PSCI
 
# integration tests 
after_build:
  - ps: . ./examples/various/BuildDeploy/build.ps1
  - ps: . ./examples/webAndDatabase/BuildDeploy/build.ps1
  - ps: . ./examples/various/bin/DeployScripts/deploy.ps1 -Environment Dev -TokensOverride @{ 'Credentials.UserName' = "$($env:COMPUTERNAME)\$($env:PSCIWinRmUser)"; Password = $env:PSCIWinRmPassword; 'Topology.Nodes' = 'localhost' }
  - ps: . ./examples/webAndDatabase/bin/DeployScripts/deploy.ps1 -Environment Test -TokensOverride @{ 'UserName' = "$($env:COMPUTERNAME)\$($env:PSCIWinRmUser)"; Password = $env:PSCIWinRmPassword; Nodes = 'localhost' }
  - ps: . ./examples/builtinSteps/BuildDeploy/deploy.ps1 -Environment Test -TokensOverride @{ 'UserName' = "$($env:COMPUTERNAME)\$($env:PSCIWinRmUser)"; Password = $env:PSCIWinRmPassword; Nodes = 'localhost' }
    
deploy:
  - provider: GitHub
    auth_token: $(GithubAuthToken)
    draft: true
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
#  - provider: NuGet
#    api_key: $(NugetApiKey)
#    artifact: PSCI.zip
#    on:
#      branch: master
#      appveyor_repo_tag: true

after_deploy:
  - ps: Publish-Module -Path (Join-Path -Path $env:APPVEYOR_BUILD_FOLDER -ChildPath "PSCI") -NuGetApiKey $env:PowershellGalleryApiKey -Verbose -Force
    on:
      branch: master
      appveyor_repo_tag: true

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
